/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLOCK_H_RPCGEN
#define _CLOCK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct timetuple {
	int hours;
	int minutes;
	int seconds;
	long u_seconds;
};
typedef struct timetuple timetuple;

#define TIME_PROG 0x23451111
#define TIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TIME 1
extern  timetuple * time_1(void *, CLIENT *);
extern  timetuple * time_1_svc(void *, struct svc_req *);
extern int time_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TIME 1
extern  timetuple * time_1();
extern  timetuple * time_1_svc();
extern int time_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_timetuple (XDR *, timetuple*);

#else /* K&R C */
extern bool_t xdr_timetuple ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLOCK_H_RPCGEN */
