/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clock.h"
#include <time.h>

timetuple *
time_1_svc(void *argp, struct svc_req *rqstp)
{
	static timetuple  result;

	/*
	 * insert server code here
	 */
	time_t rawtime;
	struct tm * timeinfo;
	rawtime = time(NULL);
	timeinfo = localtime ( &rawtime );
	result.hours = timeinfo->tm_hour;
	result.minutes = timeinfo->tm_min;
	result.seconds = timeinfo->tm_sec;
	printf("Server time sent: %d:%d:%d\n", result.hours,result.minutes,result.seconds);

	return &result;
}
