/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clock.h"

#include <sys/time.h>
#include <time.h>

timetuple *
time_1_svc(void *argp, struct svc_req *rqstp)
{
	static timetuple  result;

	/*
	 * insert server code here
	 */
	struct timeval tv;
	struct tm * timeinfo;
	gettimeofday(&tv, NULL); 
	timeinfo = localtime(&tv.tv_sec);

	result.hours = timeinfo->tm_hour;
	result.minutes = timeinfo->tm_min;
	result.seconds = timeinfo->tm_sec;
	result.u_seconds = tv.tv_usec;
	printf("Server time sent: %d:%d:%d.%ld\n", result.hours,result.minutes,result.seconds,result.u_seconds);

	return &result;
}
