/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLOCK_H_RPCGEN
#define _CLOCK_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct timetuple {
	int hours;
	int minutes;
	int seconds;
	long u_seconds;
};
typedef struct timetuple timetuple;
#ifdef __cplusplus
extern "C" bool_t xdr_timetuple(XDR *, timetuple*);
#elif __STDC__
extern  bool_t xdr_timetuple(XDR *, timetuple*);
#else /* Old Style C */
bool_t xdr_timetuple();
#endif /* Old Style C */


#define TIME_PROG ((rpc_uint)0x23451111)
#define TIME_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define TIME ((rpc_uint)1)
extern "C" timetuple * time_1(void *, CLIENT *);
extern "C" timetuple * time_1_svc(void *, struct svc_req *);

#elif __STDC__
#define TIME ((rpc_uint)1)
extern  timetuple * time_1(void *, CLIENT *);
extern  timetuple * time_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define TIME ((rpc_uint)1)
extern  timetuple * time_1();
extern  timetuple * time_1_svc();
#endif /* Old Style C */

#endif /* !_CLOCK_H_RPCGEN */
