/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clock.h"

bool_t
xdr_timetuple (XDR *xdrs, timetuple *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->hours))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->minutes))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->seconds))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_serverTime (XDR *xdrs, serverTime *objp)
{
	register int32_t *buf;

	 if (!xdr_timetuple (xdrs, &objp->receive))
		 return FALSE;
	 if (!xdr_timetuple (xdrs, &objp->send))
		 return FALSE;
	return TRUE;
}
